language: go
## https://docs.travis-ci.com/user/languages/go/
## 每种语言都有自己的默认的 install 和 script
## 如果不指定，就会默认执行命令。失败则失败。

services:
  - docker

sudo: required

install:
  - /bin/bash autobuild.sh build  

script:
 - /bin/bash autobuild.sh pull
  
