# https://docs.travis-ci.com/user/build-stages/share-docker-image/
dist: trusty # The Ubuntu distribution to use

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$HUB_PASSWD" | docker login -u "$HUB_USER" --password-stdin
      - docker build -t java-jdk alpine-jdk/
      - docker images
      - docker tag java-jdk $HUB_USER/java-jdk
      - docker push $HUB_USER/java-jdk
    - stage: test
      script: docker run --rm $HUB_USER/java-jdk java -version
    - script: docker run --rm $HUB_USER/java-jdk java -version
